name = "spinmamabonus-fr"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=spinmamabonus.fr"
HMAC_KEY = "cdd20b7a603e18e7a9685580232aed4beb8f37f0a07bf8164ad7ff34e0903993"
COOKIE_NAME = "ag8"
PLAY_PATH = "try-now"
BUTTON_ID = "p6f3489ef76a16d70e77b7c98c030a28d"
GATE_SALT = "7312d2eaa0c1c781"
GO_URLS = "[\"https://monitorre.top/go/ref\", \"https://firespot.click/go/ref\", \"https://fintechfox.click/go/ref\", \"https://buffout.click/go/ref\"]"
GO_TOKEN = "6c27a2676e6fb97970145a1c9daa1d717ea137c80518a24c"
GO_COOKIE = "mrc8"
CTA_SELECTOR = ".play-button"
